<a href="https://colab.research.google.com/github/gopiBNK/files/blob/main/code4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
rows = 4
cols = 5
data_matrix = np.array([
    [1.2, 3.5, 5.7, 2.1, 4.4],
    [6.8, 2.4, 3.6, 8.7, 5.9],
    [4.3, 7.1, 8.2, 1.4, 3.7],
    [9.8, 2.1, 4.5, 6.2, 7.0]
])
transposed_matrix = data_matrix.T
cov_matrix = np.cov(transposed_matrix, rowvar=False)
corr_matrix = np.corrcoef(transposed_matrix, rowvar=False)
print(f'Original Matrix ({rows}x{cols}):\n{data_matrix}\n')
print(f'Covariance Matrix ({rows}x{rows}):\n{cov_matrix}\n')
print(f'Correlation Matrix ({rows}x{rows}):\n{corr_matrix}\n')


Original Matrix (4x5):
[[1.2 3.5 5.7 2.1 4.4]
 [6.8 2.4 3.6 8.7 5.9]
 [4.3 7.1 8.2 1.4 3.7]
 [9.8 2.1 4.5 6.2 7. ]]

Covariance Matrix (4x4):
[[ 3.207  -2.8255  3.121  -2.867 ]
 [-2.8255  6.327  -6.3865  5.228 ]
 [ 3.121  -6.3865  7.443  -4.4235]
 [-2.867   5.228  -4.4235  8.227 ]]

Correlation Matrix (4x4):
[[ 1.         -0.62725902  0.6388079  -0.5581584 ]
 [-0.62725902  1.         -0.93065773  0.72462934]
 [ 0.6388079  -0.93065773  1.         -0.56528996]
 [-0.5581584   0.72462934 -0.56528996  1.        ]]

